### ISSUE TITLE
Fill in wiring

### ISSUE THREAD

**Issue by nicholasnbg** [realestate-com-au/applied-scala#11]
# Overview 

See issue #10 for greater context

As part of an effort to streamline the course, it was agreed that filling in the 'wiring' ahead of time would be a positive change. The amount of time currently spent by presenters rushing through and filling making changes to `AppRuntime` and `AppRoutes` just adds unnecessary noise to the course and is thought of as 'low impact' in teams of what we are trying to teach students.

# In Scope
- Wiring for `GET movies` endpoint
- Wiring for `GET movie` endpoint
- Wiring for `GET enrichedMovie` endpoint
- Wiring for `POST movie` endpoint
- Wiring for `POST movie/id/review` endpoint

# Out of scope
- Wiring for endpoint `?`

# Questions
- What endpoint is most appropriate to not fill in?

- How can we indicate that we have already filled in the wiring, and point curious students in the right direction?

**Comment by wjlow** [comment]
> What endpoint is most appropriate to not fill in?

I think `GET movie` is appropriate to not fill in. It's the first endpoint the students work on.

> How can we indicate that we have already filled in the wiring, and point curious students in the right direction?

I think updating the `README.md` that's in each `urls` package to reflect this is good. I plan to point students to the `README.md` file often and make sure they know that's what they should refer to for directions.

**Comment by millyrowboat** [comment]
> I think GET movie is appropriate to not fill in. It's the first endpoint the students work on.
👍 agree

> How can we indicate that we have already filled in the wiring, and point curious students in the right direction?

I wonder if we can have two files, one filled out we use in course, and one not filled out that people can do themselves? That also might be a nice pattern to be like "here's some extra work to test your knowledge if you want"

But yes also READMEs should be useful and up to date

**Comment by wjlow** [comment]
I updated the comments and the README to communicate these things accurately
