### ISSUE TITLE
Fill in Day 2 Codecs

### ISSUE THREAD

**Issue by nicholasnbg** [realestate-com-au/applied-scala#12]
# Overview

See issue #10 for context

As part of an effort to streamline the course, it was agreed that filling in the encoders and decoders for day 2 ahead of time would be a positive change. 

# In Scope
- Fill out `MovieValidationError` encoder
- Fill out `NewMovieRequest` decoder
- Fill out `NewReviewRequest` decoder
- Fill out `ReviewId` encoder
- Fill out `ReviewValidationError` encoder

**Comment by wjlow** [comment]
I can do this.

**Comment by wjlow** [comment]
## In Scope

`MovieId` encoder
